<?php

namespace App\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ModelUserTransformerExtension extends AbstractTypeExtension
{
    public static function getExtendedTypes(): iterable
    {
        return [TextType::class];
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        if (isset($options['model_user_transformer'])) {
            $builder->addModelTransformer($options['model_user_transformer']);
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults([
            'model_user_transformer' => null,
            'invalid_message' => 'The upline that you enter is not present.'
        ]);
    }
}
